/**************************************************************************
 *
 *  Copyright 2008, Roger Brown
 *
 *  This file is part of somFree.
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 * $Id$
 */

#include <somobj.idl>

module somtesta
{
	union u_one switch (short)
	{
		case 1: octet data_1;
		case 2: short data_2;
		case 4: long data_4;
		default: string data_z;
	};

	union u_two switch (char)
	{
		case 1: char data_1;
		case 2: char data_2;
	};

	union u_three switch (char)
	{
		case 1: char data_1;
		case 2: long data_2;
	};

	union u_four switch (char)
	{
		case 1: char data_1;
		case 2: short data_2;
	};

	union u_five switch (short)
	{
		case 1: char data_1;
		case 2: char data_2;
	};

	union u_six switch (short)
	{
		case 1: char data_1;
		case 2: short data_2;
	};

	union u_seven switch (short)
	{
		case 1: char data_1;
		case 2: long data_2;
	};

	union u_eight switch (long)
	{
		case 1: char data_1;
		case 2: char data_2;
	};

	union u_nine switch (long)
	{
		case 1: char data_1;
		case 2: short data_2;
	};

	union u_ten switch (long)
	{
		case 1: long data_1;
		case 2: char data_2;
	};

	union u_eleven switch (long)
	{
		case 1: long data_1;
		case 2: double data_2;
	};

	enum roo { one, two, three };

	union u_roo switch (roo)
	{
		case one: long data_one;
		case two: long data_two;
		case three: long data_three;
	};

	struct s_one { octet b; };

	struct s_two
	{
		octet o;
		s_one o2;
	};

	struct s_align_octet
	{
		octet o;
		octet o2;
	};

	struct s_align_short
	{
		octet o;
		short o2;
	};

	struct s_align_long
	{
		octet o;
		long o2;
	};

	struct s_align_float
	{
		octet o;
		float o2;
	};

	struct s_align_double
	{
		octet o;
		double o2;
	};

	struct s_align_string
	{
		octet o;
		string o2;
	};

	struct s_align_sequence
	{
		octet o;
		sequence<octet> o2;
	};

	struct s_align_array
	{
		octet o;
		octet o2[1];
	};

	struct s_align_TypeCode
	{
		octet o;
		TypeCode o2;
	};

	struct s_align_any
	{
		octet o;
		any o2;
	};

	struct s_align_SOMObject
	{
		octet o;
		SOMObject o2;
	};
};
