/**************************************************************************
 *
 *  Copyright 2008, Roger Brown
 *
 *  This file is part of somFree.
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 * $Id$
 */

#ifndef simple_idl
#define simple_idl
#include <somobj.idl>
#include <somref.idl>
#include <somdobj.idl>
#include <somcls.idl>
module Simple
{
	typedef octet an_array[4];
/*	typedef float a_matrix[3][3];*/
	typedef double my_array[5][6][7];

	typedef my_array deeper[8][9][10];

	typedef float a_matrix[9];

	interface SimpleClass;
	interface SimpleBase;
	interface SimpleBase2;
	interface SimpleBase3;
	interface Useless;
	interface SimpleBase4;
	interface SimpleObject;
	interface SimpleClass :
		SOMClass
	{
		void ifSimple();
#ifdef __SOMIDL__
		implementation
		{
			releaseorder : ifSimple;
		};
#endif /* __SOMIDL__ */
	};
	interface SimpleBase :
		SOMRefObject
	{
		attribute string display_name;
#ifdef __SOMIDL__
		implementation
		{
			releaseorder : _get_display_name,_set_display_name;
		};
#endif /* __SOMIDL__ */
	};
	interface SimpleBase2 :
		SimpleBase
	{
		attribute string display_name_2;
#ifdef __SOMIDL__
		implementation
		{
			releaseorder : _get_display_name_2,_set_display_name_2;
		};
#endif /* __SOMIDL__ */
	};
	interface SimpleBase3 :
		SimpleBase2
	{
		attribute string display_name_3;
#ifdef __SOMIDL__
		implementation
		{
			releaseorder : _get_display_name_3,_set_display_name_3;
		};
#endif /* __SOMIDL__ */
	};
	interface Useless :
		SimpleBase3,
		SOMDObject
	{
		attribute string crap_3;
#ifdef __SOMIDL__
		implementation
		{
			releaseorder : _get_crap_3,_set_crap_3;
		};
#endif /* __SOMIDL__ */
	};
	interface SimpleBase4 :
		Useless
	{
		attribute string display_name_4;
#ifdef __SOMIDL__
		implementation
		{
			releaseorder : _get_display_name_4,_set_display_name_4;
		};
#endif /* __SOMIDL__ */
	};
	interface SimpleObject :
		SimpleBase4
	{
		void m1();
		void m2(in string m);
		attribute string banana;
		void in_matrix(in a_matrix my_matrix);
		void out_matrix(out a_matrix my_matrix);
		long return_long();
		short return_short();
		unsigned long return_ulong();
		unsigned short return_ushort();
		float return_float();
		double return_double();
		char return_char();
		octet return_octet();
		boolean return_boolean();
		void return_void();
		string return_string();
		typedef short i;
		i return_i();
		any return_any();
		SOMObject return_object();
		TypeCode return_tc();

		void in_array(in an_array array);
		void out_array(out an_array array);
		void inout_array(inout an_array array);

		attribute my_array mar;
		attribute deeper mar2;
		void put_my_array(out my_array f);	
		void fetch_my_array(out my_array f);

		struct h
		{
			short a;
			short b;
		};
		h return_struct();
		sequence<octet> return_seq();
#ifdef __SOMIDL__
		implementation
		{
			releaseorder : 
				m1,
				m2,
				_get_banana,
				_set_banana,
				return_long,
				return_short,
				return_ulong,
				return_ushort,
				return_float,
				return_double,
				return_char,
				return_octet,
				return_boolean,
				return_void,
				return_string,
				return_i,
				return_any,
				return_object,
				return_tc,
				return_struct,
				return_seq,
				in_array,
				out_array,
				inout_array;
			metaclass = SimpleClass;
		};
#endif /* __SOMIDL__ */
	};
	interface M_Simplest : SOMClass
	{
		void flim();
		implementation
		{
			releaseorder: flim;	
		};
	};
	interface Simplest : SOMObject
	{
		implementation
		{
			metaclass = M_Simplest;
		};
	};
	interface Simplex : Simplest, SimpleObject
	{
		void flam();
		implementation
		{
			releaseorder: flam;	
		};
	};

	interface octet_class : SOMObject
	{
		attribute octet b;

		implementation
		{
			releaseorder: _get_b,_set_b;
			override: somDumpSelfInt;
			functionprefix=octet_;
		};
	};

	interface double_class : SOMObject
	{
		attribute double b;

		implementation
		{
			releaseorder: _get_b,_set_b;
			override: somDumpSelfInt;
			functionprefix=double_;
		};
	};

	interface float_class : SOMObject
	{
		attribute float b;

		implementation
		{
			releaseorder: _get_b,_set_b;
			override: somDumpSelfInt;
			functionprefix=float_;
		};
	};

	interface short_class : SOMObject
	{
		attribute short b;

		implementation
		{
			releaseorder: _get_b,_set_b;
			override: somDumpSelfInt;
			functionprefix=short_;
		};
	};

	interface octet_octet_class : octet_class
	{
		attribute octet v;

		implementation
		{
			releaseorder: _get_v,_set_v;
			override: somDumpSelfInt;
			functionprefix=octet_octet_;
		};
	};

	interface octet_double_class : octet_class
	{
		attribute double v;

		implementation
		{
			releaseorder: _get_v,_set_v;
			override: somDumpSelfInt;
			functionprefix=octet_double_;
		};
	};

	interface octet_float_class : octet_class
	{
		attribute float v;

		implementation
		{
			releaseorder: _get_v,_set_v;
			override: somDumpSelfInt;
			functionprefix=octet_float_;
		};
	};

	interface octet_short_class : octet_class
	{
		attribute short v;

		implementation
		{
			releaseorder: _get_v,_set_v;
			override: somDumpSelfInt;
			functionprefix=octet_short_;
		};
	};
};
#endif /* simple_idl */
